### ISSUE TITLE
inference speed

### ISSUE THREAD

**Issue by STLIFE97** [LiJiahang617/Road-Former#2]
Hello，in the article, it states that 'RoadFormer yields an inference speed of approximately 20 FPS when processing images at a resolution of 352 × 640 pixels on an NVIDIA RTX 3090 GPU.' Does the 'inference speed' include the time taken to calculate the surface normal map?

**Comment by LiJiahang617** [comment]
Hello, thanks for following our work! 
In our implementation, we pre-process all of our depth map to surface normal, and directly send the SN to our model, so the 20 frames/second does not include the time of SN estimator. But considering the D2NT (our implementation for SN estimation is a real-time algorithm, so it won't take long time). Please feel free for any further question.

**Comment by STLIFE97** [comment]
Thank you very much for your detailed response!

Additionally, I would like to inquire if you could provide the specific time it takes to compute the surface normals? If possible, an approximate value or time range would be very helpful to us. Also, did you use the SNE method for computing the surface normals?

**Comment by LiJiahang617** [comment]
As mentioned in the article, we used D2NT to estimate SN from the dense depth map (with corresponding intrinsic matrix). But we did not recode the processing time for calculating the estimation. Maybe you can refer to our previous works about this (D2NT,3F2N). I think the SNE module won't take too long considering they are real-time. Please feel free for any further question!
