### ISSUE TITLE
When will the checkpoints be released?

### ISSUE THREAD

**Issue by Stark320** [LiJiahang617/Road-Former#4]
Especiallly checkpoints of RGB-T Segmentation on MFNet dataset.

**Comment by LiJiahang617** [comment]
All results mentioned in our papers are reproducible, since the checkpoints are too large, so we do not plan to release them, you may retrain our models on these datasets.

**Comment by LiJiahang617** [comment]
Please leave your email or wechat, maybe we can provide it.

**Comment by iacopo97** [comment]
Hi thank you for your work, I am interested in the weights too, I have sent you a mail.

**Comment by jianxinhuang3** [comment]
> Hi thank you for your work, I am interested in the weights too, I have sent you a mail.

Hello, the weights have been sent to you via email.

**Comment by jianxinhuang3** [comment]
The checkpoint trained on MFNet with a ConvNeXt-L backbone can be accessed via the following link:

https://drive.google.com/file/d/1PgIblZHonwMg4sotA1hkLG10lrV2T1cc/view?usp=sharing

We do not plan to release any other checkpoints, as all results reported in the paper can be reproduced using the publicly available code.
