### ISSUE TITLE
Training on FMB dataset

### ISSUE THREAD

**Issue by yuwenmichael** [LiJiahang617/Road-Former#5]
Do you train the model together with the background class (meaning there are 15 classes in total) or did you ignore the index for the background class? Could you provide the coding part that you specifcally ignore the background class if you ignore it? Also, have you included the background class for the final mIoU (i.e., you sum up 13 classes, excluding background and bicycle then divided by 13 for final result)?

**Comment by jianxinhuang3** [comment]
Hi!

We ignored the index of the background class during both training and testing.

The definition of the fmb dataset can be found in this file: https://github.com/LiJiahang617/Road-Former/blob/main/mmseg_custom/datasets/mmfmb.py
