### ISSUE TITLE
Train dataset of MFNet

### ISSUE THREAD

**Issue by iacopo97** [LiJiahang617/Road-Former#6]
Hi, thank you for your work. Could you provide me the name of the files you used in training set? In order to be sure to reproduce correctly your result.

**Comment by LiJiahang617** [comment]
Hi, we used the same data-split strategy as all other related works, you may refer to the original MFNet paper. I'm afraid i do not have a file list cause we directly downloaded it and trained our model. If you had any further quesion, feel free to contact us!

**Comment by iacopo97** [comment]
Thank you very much. Therefore have you used the same train.txt file of the original dataset to extract your train folder?

**Comment by LiJiahang617** [comment]
Yes, as mentioned in our paper and my previous response.

**Comment by iacopo97** [comment]
Thank you very much. Is it possible to get the checkpoint of the network on FMB dataset?

**Comment by LiJiahang617** [comment]
Sorry, the checkpoint was stored on our server, we have cleaned it, you may reproduce it by yourself.

**Comment by iacopo97** [comment]
Thank you very much, for your kind answer to my doubts. I will close the issue
